version: 2
jobs:
  build:
    working_directory: ~/Deinok.System.RandomExtensions/
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      
      # Restore-Build
      - restore_cache:
          key: NUGET
      - run:
          name: Test
          command: dotnet test
          working_directory: ./tests/Deinok.System.RandomExtensions.Tests/
      - save_cache:
          key: NUGET
          paths:
            - ~/.nuget/
